owner: geometry-labs
repo: icon-status-page

sites:
  - name: Prod Mainnet Tracker Frontend
    url: https://tracker.icon.community/
  - name: Prod Mainnet Blocks Service
    url: https://tracker.icon.community/api/v1/blocks
  - name: Prod Mainnet Transactions Service
    url: https://tracker.icon.community/api/v1/transactions
  - name: Prod Mainnet Logs Service
    url: https://tracker.icon.community/api/v1/logs
  - name: Prod Mainnet Addresses Service
    url: https://tracker.icon.community/api/v1/addresses
  - name: Prod Mainnet Governance Service
    url: https://tracker.icon.community/api/v1/preps
  - name: Prod Mainnet Contracts Service
    url: https://tracker.icon.community/api/v1/contracts
  - name: US Mainnet Tracker Frontend
    url: https://usw2.tracker.icon.geometry.io/
  - name: US Mainnet Blocks Service
    url: https://usw2.tracker.icon.geometry.io/api/v1/blocks
  - name: US Mainnet Transactions Service
    url: https://usw2.tracker.icon.geometry.io/api/v1/transactions
  - name: US Mainnet Logs Service
    url: https://usw2.tracker.icon.geometry.io/api/v1/logs
  - name: US Mainnet Addresses Service
    url: https://usw2.tracker.icon.geometry.io/api/v1/addresses
  - name: US Mainnet Governance Service
    url: https://usw2.tracker.icon.geometry.io/api/v1/preps
  - name: US Mainnet Contracts Service
    url: https://usw2.tracker.icon.geometry.io/api/v1/contracts
  - name: EU Mainnet Tracker Frontend
    url: https://euw1.tracker.icon.geometry.io/
  - name: EU Mainnet Blocks Service
    url: https://euw1.tracker.icon.geometry.io/api/v1/blocks
  - name: EU Mainnet Transactions Service
    url: https://euw1.tracker.icon.geometry.io/api/v1/transactions
  - name: EU Mainnet Logs Service
    url: https://euw1.tracker.icon.geometry.io/api/v1/logs
  - name: EU Mainnet Addresses Service
    url: https://euw1.tracker.icon.geometry.io/api/v1/addresses
  - name: EU Mainnet Governance Service
    url: https://euw1.tracker.icon.geometry.io/api/v1/preps
  - name: EU Mainnet Contracts Service
    url: https://euw1.tracker.icon.geometry.io/api/v1/contracts
  - name: Prod Sejong Tracker Frontend
    url: https://explorer.sejong.geometry.io/
  - name: Prod Sejong Blocks Service
    url: https://explorer.sejong.geometry.io/api/v1/blocks
  - name: Prod Sejong Transactions Service
    url: https://explorer.sejong.geometry.io/api/v1/transactions
  - name: Prod Sejong Logs Service
    url: https://explorer.sejong.geometry.io/api/v1/logs
  - name: Prod Sejong Addresses Service
    url: https://explorer.sejong.geometry.io/api/v1/addresses
  - name: Prod Sejong Governance Service
    url: https://explorer.sejong.geometry.io/api/v1/preps
  - name: Prod Sejong Contracts Service
    url: https://explorer.sejong.geometry.io/api/v1/contracts
  - name: Dev Tracker Frontend
    url: https://explorer.icon.geometry-dev.net/
  - name: Dev Blocks Service
    url: https://explorer.icon.geometry-dev.net/api/v1/blocks
  - name: Dev Transactions Service
    url: https://explorer.icon.geometry-dev.net/api/v1/transactions
  - name: Dev Logs Service
    url: https://explorer.icon.geometry-dev.net/api/v1/logs
  - name: Dev Addresses Service
    url: https://explorer.icon.geometry-dev.net/api/v1/addresses
  - name: Dev Governance Service
    url: https://explorer.icon.geometry-dev.net/api/v1/preps
  - name: Dev Contracts Service
    url: https://explorer.icon.geometry-dev.net/api/v1/contracts


status-website:
  theme: dark
  cname: status.icon.geometry.io
  logoUrl: https://raw.githubusercontent.com/geometry-labs/icon-status-page/master/assets/icon-logo.png
  name: ICON Blockchain
  introTitle: |
    Status page for the **ICON Blockchain**
    Endpoints supported by **Geometry Labs**
  favicon: https://raw.githubusercontent.com/geometry-labs/icon-status-page/master/assets/icon-favicon.png
  metaTags:
    - name: "ICON Status"
    - content: "noIndex"
  introMessage: |

  navbar:
    - title: Status
      href: /
    - title: Grafana
      href: https://grafana.icon.geometry.io
    - title: Kibana - US
      href: https://kibana.us-west-2.aws.geometry.io/
    - title: Kibana - EU
      href: https://kibana.eu-west-2.aws.geometry.io/
    - title: GitHub
      href: https://github.com/$OWNER/icon-explorer

