owner: geometry-labs
repo: icon-status-page

sites:
  # API NODES
  - name: Prod ICON RPC
    url: https://api.icon.geometry.io/api/v3
    method: POST
    body: '{"jsonrpc": "2.0","method": "icx_getLastBlock","id": 1234}'

  # GLOBAL MAINNET
  - name: Prod Mainnet Tracker Frontend
    url: https://tracker.icon.community/

  - name: Prod Mainnet Blocks Service (RPC)
    url: https://tracker.icon.community/api/v1/blocks
  - name: Prod Mainnet Blocks Service (WS)
    check: "ws"
    maxResponseTime: 10000
    url: https://tracker.icon.community/ws/v1/blocks

  - name: Prod Mainnet Transactions Service (RPC)
    url: https://tracker.icon.community/api/v1/transactions
  - name: Prod Mainnet Transactions Service (WS)
    check: "ws"
    maxResponseTime: 10000
    url: https://tracker.icon.community/ws/v1/transactions

  - name: Prod Mainnet Logs Service (RPC)
    url: https://tracker.icon.community/api/v1/logs
  - name: Prod Mainnet Transactions Service (WS)
    check: "ws"
    maxResponseTime: 10000
    url: https://tracker.icon.community/ws/v1/logs

  - name: Prod Mainnet Addresses Service
    url: https://tracker.icon.community/api/v1/addresses
  - name: Prod Mainnet Governance Service
    url: https://tracker.icon.community/api/v1/preps
  - name: Prod Mainnet Contracts Service
    url: https://tracker.icon.community/api/v1/contracts
  - name: Prod Mainnet Metrics Service
    url: https://tracker.icon.community/api/v1/metrics/supply

#  # US MAINNET
#  - name: US Mainnet Tracker Frontend
#    url: https://usw2.tracker.icon.geometry.io/
#
#  - name: US Mainnet Blocks Service (RPC)
#    url: https://usw2.tracker.icon.geometry.io/api/v1/blocks
#  - name: US Mainnet Blocks Service (WS)
#    check: "ws"
#    maxResponseTime: 10000
#    url: https://usw2.tracker.icon.geometry.io/ws/v1/blocks
#
#  - name: US Mainnet Transactions Service (RPC)
#    url: https://usw2.tracker.icon.geometry.io/api/v1/transactions
#  - name: US Mainnet Transactions Service (WS)
#    check: "ws"
#    maxResponseTime: 10000
#    url: https://usw2.tracker.icon.geometry.io/ws/v1/transactions
#
#  - name: US Mainnet Logs Service (RPC)
#    url: https://usw2.tracker.icon.geometry.io/api/v1/logs
#  - name: US Mainnet Transactions Service (WS)
#    check: "ws"
#    maxResponseTime: 10000
#    url: https://usw2.tracker.icon.geometry.io/ws/v1/logs
#
#  - name: US Mainnet Addresses Service
#    url: https://usw2.tracker.icon.geometry.io/api/v1/addresses
#  - name: US Mainnet Governance Service
#    url: https://usw2.tracker.icon.geometry.io/api/v1/preps
#  - name: US Mainnet Contracts Service
#    url: https://usw2.tracker.icon.geometry.io/api/v1/contracts
#  - name: US Prod Mainnet Metrics Service
#    url: https://usw2.tracker.icon.geometry.io/api/v1/metrics/supply

  # EU MAINNET
  - name: EU Mainnet Tracker Frontend
    url: https://euw1.tracker.icon.geometry.io/

  - name: EU Mainnet Blocks Service
    url: https://euw1.tracker.icon.geometry.io/api/v1/blocks
  - name: US Mainnet Blocks Service (WS)
    check: "ws"
    maxResponseTime: 10000
    url: https://euw1.tracker.icon.geometry.io/ws/v1/blocks

  - name: EU Mainnet Transactions Service
    url: https://euw1.tracker.icon.geometry.io/api/v1/transactions
  - name: US Mainnet Transactions Service (WS)
    check: "ws"
    maxResponseTime: 10000
    url: https://euw1.tracker.icon.geometry.io/ws/v1/transactions

  - name: EU Mainnet Logs Service
    url: https://euw1.tracker.icon.geometry.io/api/v1/logs
  - name: US Mainnet Transactions Service (WS)
    check: "ws"
    maxResponseTime: 10000
    url: https://euw1.tracker.icon.geometry.io/ws/v1/logs

  - name: EU Mainnet Addresses Service
    url: https://euw1.tracker.icon.geometry.io/api/v1/addresses
  - name: EU Mainnet Governance Service
    url: https://euw1.tracker.icon.geometry.io/api/v1/preps
  - name: EU Mainnet Contracts Service
    url: https://euw1.tracker.icon.geometry.io/api/v1/contracts
  - name: EU Prod Mainnet Metrics Service
    url: https://euw1.tracker.icon.geometry.io/api/v1/metrics/supply

  - name: Prod Mainnet RPC
    url: https://api.icon.community/api/v3
    method: POST
    body: '{"jsonrpc": "2.0","method": "icx_getLastBlock","id": 1234}'
  - name: Prod Mainnet Amsterdam RPC
    url: https://api.mainnet.ams.vultr.icon.community/api/v3
    method: POST
    body: '{"jsonrpc": "2.0","method": "icx_getLastBlock","id": 1234}'
  - name: Prod Mainnet Singapore RPC
    url: https://api.mainnet.sng.vultr.icon.community/api/v3
    method: POST
    body: '{"jsonrpc": "2.0","method": "icx_getLastBlock","id": 1234}'

  - name: Prod Sejong RPC
    url: https://api.sejong.icon.community/api/v3
    method: POST
    body: '{"jsonrpc": "2.0","method": "icx_getLastBlock","id": 1234}'
  - name: Prod Sejong Amsterdam RPC
    url: https://api.sejong.ams.vultr.icon.community/api/v3
    method: POST
    body: '{"jsonrpc": "2.0","method": "icx_getLastBlock","id": 1234}'
  - name: Prod Sejong Singapore RPC
    url: https://api.sejong.sng.vultr.icon.community/api/v3
    method: POST
    body: '{"jsonrpc": "2.0","method": "icx_getLastBlock","id": 1234}'

  - name: Prod Lisbon RPC
    url: https://api.lisbon.icon.community/api/v3
    method: POST
    body: '{"jsonrpc": "2.0","method": "icx_getLastBlock","id": 1234}'
  - name: Prod Lisbon Amsterdam RPC
    url: https://api.lisbon.ams.vultr.icon.community/api/v3
    method: POST
    body: '{"jsonrpc": "2.0","method": "icx_getLastBlock","id": 1234}'
  - name: Prod Lisbon Singapore RPC
    url: https://api.lisbon.sng.vultr.icon.community/api/v3
    method: POST
    body: '{"jsonrpc": "2.0","method": "icx_getLastBlock","id": 1234}'

  - name: Prod Berlin RPC
    url: https://api.berlin.icon.community/api/v3
    method: POST
    body: '{"jsonrpc": "2.0","method": "icx_getLastBlock","id": 1234}'
  - name: Prod Berlin Amsterdam RPC
    url: https://api.berlin.ams.vultr.icon.community/api/v3
    method: POST
    body: '{"jsonrpc": "2.0","method": "icx_getLastBlock","id": 1234}'
  - name: Prod Berlin Singapore RPC
    url: https://api.berlin.sng.vultr.icon.community/api/v3
    method: POST
    body: '{"jsonrpc": "2.0","method": "icx_getLastBlock","id": 1234}'


status-website:
  links:
    - rel: stylesheet
      href: https://rheannone.github.io/CSS/css/icon-status_dark-theme.css
  cname: status.icon.geometry.io
  logoUrl: https://raw.githubusercontent.com/geometry-labs/icon-status-page/master/assets/icon-logo.png
  name: ICON Blockchain
  introTitle: |
    Status page for the **ICON Blockchain**
    Endpoints supported by **Geometry Labs**
  favicon: https://raw.githubusercontent.com/geometry-labs/icon-status-page/master/assets/icon-favicon.png
  metaTags:
    - name: "ICON Status"
    - content: "noIndex"
  introMessage: |

  navbar:
    - title: Status
      href: /
    - title: Grafana
      href: https://grafana.icon.geometry.io
    - title: Kibana - US
      href: https://kibana.us-west-2.aws.geometry.io/
    - title: Kibana - EU
      href: https://kibana.eu-west-2.aws.geometry.io/
    - title: GitHub
      href: https://github.com/$OWNER/icon-explorer

